language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    - curl -L -o /tmp/0.5.2_linux_amd64.zip https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
    - unzip /tmp/0.5.2_linux_amd64.zip
    - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
    - pip install codecov
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nosetests